name: Cache Gradle
description: Improved cache for Gradle

inputs:
  cache-version:
    required: true
    default: '1'
    description: "Cache version. Change it to reset cache."
  build-cache-enabled:
    required: true
    default: 'true'
    description: "Set to 'false' to disable Gradle Build Cache"
  build-cache-for-branches-only:
    required: true
    default: 'false'
    description: "Set to 'true' to disable Gradle Build Cache for tags"
  default-branch:
    required: false
    description: "Repository default branch. Will be retrieved from GitHub if not set."

outputs:
  gradle-wrapper-cache-hit:
    description: "A boolean value to indicate an exact match was found for Gradle wrapper cache"
    value: ${{steps.gradle-wrapper.outputs.cache-hit}}
  gradle-caches-cache-hit:
    description: "A boolean value to indicate an exact match was found for Gradle caches cache"
    value: ${{steps.gradle-caches.outputs.cache-hit}}

runs:
  using: composite
  steps:
  - name: Cache Gradle wrapper
    id: gradle-wrapper
    uses: actions/cache@v3
    with:
      key: v${{inputs.cache-version}}-${{runner.os}}-gradle-wrapper-${{hashFiles('**/gradle/wrapper/gradle-wrapper.properties')}}
      path: |
        ${{env.GRADLE_USER_HOME || '~/.gradle'}}/wrapper/dists
  - name: Cache Gradle caches
    id: gradle-caches
    uses: actions/cache@v3
    with:
      key: v${{inputs.cache-version}}-${{runner.os}}-gradle-caches-${{hashFiles('**/gradle/wrapper/gradle-wrapper.properties', '**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', '**/gradle.lockfile', '**/*-gradle.lockfile')}}
      path: |
        ${{env.GRADLE_USER_HOME || '~/.gradle'}}/caches
        ${{env.GRADLE_USER_HOME || '~/.gradle'}}/jdks
        ${{env.GRADLE_USER_HOME || '~/.gradle'}}/notifications
  - name: Cleanup Gradle wrapper cache
    if: ${{steps.gradle-wrapper.outputs.cache-hit != 'true' || steps.gradle-caches.outputs.cache-hit != 'true'}}
    uses: remal-github-actions/cache-gradle-cleanup-wrapper@v1

  - name: Setup Gradle Build Cache
    if: ${{inputs.build-cache-enabled == 'true' && (inputs.build-cache-for-branches-only == 'false' || github.ref_type == 'branch')}}
    shell: bash
    run: |
      mkdir -p ${{env.GRADLE_USER_HOME || '~/.gradle'}}
      echo "" >> ${{env.GRADLE_USER_HOME || '~/.gradle'}}/gradle.properties
      echo "org.gradle.caching = true" >> ${{env.GRADLE_USER_HOME || '~/.gradle'}}/gradle.properties
      mkdir -p ${{env.GRADLE_USER_HOME || '~/.gradle'}}/init.d
      echo "gradle.settingsEvaluated { settings ->" > ${{env.GRADLE_USER_HOME || '~/.gradle'}}/init.d/build-cache.gradle
      echo "    settings.buildCache {" >> ${{env.GRADLE_USER_HOME || '~/.gradle'}}/init.d/build-cache.gradle
      echo "        local {" >> ${{env.GRADLE_USER_HOME || '~/.gradle'}}/init.d/build-cache.gradle
      echo "            directory = new File('${{env.GRADLE_USER_HOME || '~/.gradle'}}/.build-cache'.replaceFirst('^~/', System.getProperty('user.home') + '/'))" >> ${{env.GRADLE_USER_HOME || '~/.gradle'}}/init.d/build-cache.gradle
      echo "            println directory" >> ${{env.GRADLE_USER_HOME || '~/.gradle'}}/init.d/build-cache.gradle
      echo "        }" >> ${{env.GRADLE_USER_HOME || '~/.gradle'}}/init.d/build-cache.gradle
      echo "    }" >> ${{env.GRADLE_USER_HOME || '~/.gradle'}}/init.d/build-cache.gradle
      echo "}" >> ${{env.GRADLE_USER_HOME || '~/.gradle'}}/init.d/build-cache.gradle
      echo ${{env.GRADLE_USER_HOME || '~/.gradle'}}/init.d/build-cache.gradle
      cat ${{env.GRADLE_USER_HOME || '~/.gradle'}}/init.d/build-cache.gradle
  - name: Retrieve repository info
    id: repository-info
    if: ${{inputs.build-cache-enabled == 'true' && (inputs.build-cache-for-branches-only == 'false' || github.ref_type == 'branch')}}
    uses: remal-github-actions/retrieve-repository-info@v1
  - name: Cache Gradle Build Cache
    if: ${{inputs.build-cache-enabled == 'true' && (inputs.build-cache-for-branches-only == 'false' || github.ref_type == 'branch')}}
    uses: actions/cache@v3
    with:
      key: v${{inputs.cache-version}}-${{runner.os}}-gradle-build-cache-${{github.job}}-${{strategy.job-index || '0'}}-${{github.base_ref || github.ref}}-${{github.sha}}-${{github.run_id}}-${{github.run_attempt}}
      restore-keys: |
        v${{inputs.cache-version}}-${{runner.os}}-gradle-build-cache-${{github.job}}-${{strategy.job-index || '0'}}-${{github.base_ref || github.ref}}-${{github.sha}}-${{github.run_id}}-
        v${{inputs.cache-version}}-${{runner.os}}-gradle-build-cache-${{github.job}}-${{strategy.job-index || '0'}}-${{github.base_ref || github.ref}}-${{github.sha}}-
        v${{inputs.cache-version}}-${{runner.os}}-gradle-build-cache-${{github.job}}-${{strategy.job-index || '0'}}-${{github.base_ref || github.ref}}-
        v${{inputs.cache-version}}-${{runner.os}}-gradle-build-cache-${{github.job}}-${{strategy.job-index || '0'}}-refs/heads/${{fromJSON(steps.repository-info.outputs.result).defaultBranch}}-
      path: |
        ${{env.GRADLE_USER_HOME || '~/.gradle'}}/.build-cache
