name: Cache Gradle
description: Improved cache for Gradle
version: 1

inputs:
  cache-version:
    required: true
    default: '1'
    description: "Cache version. Change it to reset cache."
  cache-scope:
    required: false
    default: ''
    description: "Cache scope."
  build-cache-enabled:
    required: true
    default: 'true'
    description: "Set to 'false' to disable Gradle Build Cache"
  build-cache-for-branches-only:
    required: true
    default: 'true'
    description: "Set to 'true' to disable Gradle Build Cache for tags"
  default-branch:
    required: false
    description: "Repository default branch. Will be retrieved from GitHub if not set."
  lookup-only:
    required: true
    default: 'false'
    description: "If true, only checks if cache entry exists and skips download. Does not change save cache behavior."
  github-job:
    required: true
    default: '${{github.job}}'
    description: "The current job ID"
  strategy-job-index:
    required: false
    description: "The index of the current job in the matrix"
  strategy-job-total:
    required: false
    description: "The total number of jobs in the matrix"

outputs:
  gradle-wrapper-cache-hit:
    description: "A boolean value to indicate an exact match was found for Gradle wrapper cache"
    value: ${{steps.gradle-wrapper.outputs.cache-hit}}
  gradle-caches-cache-hit:
    description: "A boolean value to indicate an exact match was found for Gradle caches cache"
    value: ${{steps.gradle-caches.outputs.cache-hit}}

runs:
  using: composite
  steps:
  - name: Calculate paths
    id: paths
    shell: bash
    run: |
      if [ -z "$GRADLE_USER_HOME" ]; then
        GRADLE_USER_HOME="~/.gradle"
      fi
      echo "gradle-user-home=$GRADLE_USER_HOME" | tee -a $GITHUB_OUTPUT

  - name: Cache Gradle wrapper
    id: gradle-wrapper
    uses: actions/cache@v5
    with:
      lookup-only: '${{inputs.lookup-only}}'
      key: v${{inputs.cache-version}}-${{runner.os}}-gradle-wrapper-${{hashFiles('**/gradle/wrapper/gradle-wrapper.properties', '**/gradle/gradle-daemon-jvm.properties')}}
      path: |
        ${{steps.paths.outputs.gradle-user-home}}/wrapper/dists

  - name: Cache Gradle caches
    id: gradle-caches
    uses: actions/cache@v5
    with:
      lookup-only: '${{inputs.lookup-only}}'
      key: v${{inputs.cache-version}}${{inputs.cache-scope && format('-{0}', inputs.cache-scope) || ''}}-${{runner.os}}-gradle-caches-${{hashFiles('**/gradle/wrapper/gradle-wrapper.properties', '**/gradle/gradle-daemon-jvm.properties', '**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', '**/gradle.lockfile', '**/*-gradle.lockfile' , '**/gradle/*.versions.toml')}}
      path: |
        ${{steps.paths.outputs.gradle-user-home}}/caches
        ${{steps.paths.outputs.gradle-user-home}}/jdks
        ${{steps.paths.outputs.gradle-user-home}}/notifications

  - name: Cleanup Gradle wrapper cache
    if: ${{steps.gradle-wrapper.outputs.cache-hit != 'true' || steps.gradle-caches.outputs.cache-hit != 'true'}}
    uses: remal-github-actions/cache-gradle-cleanup-wrapper@v1

  - name: Setup Gradle Build Cache
    if: ${{inputs.build-cache-enabled == 'true' && (inputs.build-cache-for-branches-only == 'false' || github.ref_type == 'branch')}}
    shell: bash
    run: |
      mkdir -p ${{steps.paths.outputs.gradle-user-home}}
      echo "org.gradle.caching = true" >> ${{steps.paths.outputs.gradle-user-home}}/gradle.properties
      echo ::group::${{steps.paths.outputs.gradle-user-home}}/gradle.properties
      cat ${{steps.paths.outputs.gradle-user-home}}/gradle.properties
      echo "::endgroup::"
      mkdir -p ${{steps.paths.outputs.gradle-user-home}}/init.d
      cat <<EOF > ${{steps.paths.outputs.gradle-user-home}}/init.d/build-cache.gradle
      import org.gradle.util.GradleVersion
      if (GradleVersion.current() < GradleVersion.version('4.0')) {
        return
      }
      gradle.settingsEvaluated { settings ->
        settings.buildCache.local {
          String buildCacheDirPath = '''${{steps.paths.outputs.gradle-user-home}}/.build-cache'''
          if (buildCacheDirPath == '~' || buildCacheDirPath.startsWith('~/')) {
            buildCacheDirPath = System.getProperty('user.home') + buildCacheDirPath.substring(1)
          }
          File buildCacheDir = new File(buildCacheDirPath)
          //println "buildCacheDir=" + buildCacheDir
          directory = buildCacheDir
        }
      }
      EOF
      echo ::group::${{steps.paths.outputs.gradle-user-home}}/init.d/build-cache.gradle
      cat ${{steps.paths.outputs.gradle-user-home}}/init.d/build-cache.gradle
      echo "::endgroup::"

  - name: Create Gradle Build Cache key
    if: ${{inputs.build-cache-enabled == 'true' && (inputs.build-cache-for-branches-only == 'false' || github.ref_type == 'branch')}}
    id: build-cache-key-info
    shell: bash
    env:
      BASE_KEY: v${{inputs.cache-version}}${{inputs.cache-scope && format('-{0}', inputs.cache-scope) || ''}}-${{runner.os}}-gradle-build-cache-${{hashFiles('**/gradle/wrapper/gradle-wrapper.properties', '**/gradle/gradle-daemon-jvm.properties', '**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', '**/gradle.lockfile', '**/*-gradle.lockfile' , '**/gradle/*.versions.toml')}}-${{inputs.github-job}}-${{inputs.strategy-job-index||strategy.job-index||'0'}}/${{inputs.strategy-job-total||strategy.job-total||'0'}}
    run: |
      BASE_KEY="$(printf "%s" "$BASE_KEY" | tr '{}[],;:\"'\''[:space:]' '-')"
      BASE_KEY="$(printf "%s" "$BASE_KEY" | tr -s '-')"
      echo "base-key=$BASE_KEY" | tee -a $GITHUB_OUTPUT

  - name: Cache Gradle Build Cache for branch
    if: ${{inputs.build-cache-enabled == 'true' && (inputs.build-cache-for-branches-only == 'false' || github.ref_type == 'branch')}}
    uses: actions/cache@v5
    with:
      lookup-only: '${{inputs.lookup-only}}'
      key: ${{steps.build-cache-key-info.outputs.base-key}}-refs/heads/${{github.base_ref && github.base_ref || github.ref_name}}-${{github.sha}}-${{github.run_attempt}}
      restore-keys: |
        ${{steps.build-cache-key-info.outputs.base-key}}-refs/heads/${{github.base_ref && github.base_ref || github.ref_name}}-${{github.sha}}-
        ${{steps.build-cache-key-info.outputs.base-key}}-refs/heads/${{github.base_ref && github.base_ref || github.ref_name}}-
      path: |
        ${{steps.paths.outputs.gradle-user-home}}/.build-cache
