name: Cache Gradle
description: Improved cache for Gradle

inputs:
  gradle-user-home:
    required: true
    default: '~/.gradle'
    description: "Gradle user home directory (GRADLE_USER_HOME)"
  cache-version:
    required: true
    default: '1'
    description: "Cache version. Change it to reset cache."
  build-cache-enabled:
    required: true
    default: 'true'
    description: "Set to 'false' to disable Gradle Build Cache"
  build-cache-for-branches-only:
    required: true
    default: 'false'
    description: "Set to 'true' to disable Gradle Build Cache for tags"
  default-branch:
    required: false
    description: "Repository default branch. Will be retrieved from GitHub if not set."
  lookup-only:
    required: true
    default: 'false'
    description: "If true, only checks if cache entry exists and skips download. Does not change save cache behavior."
  github-job:
    required: true
    default: '${{github.job}}'
    description: "The current job ID"
  strategy-job-index:
    required: false
    description: "The index of the current job in the matrix"
  strategy-job-total:
    required: false
    description: "The total number of jobs in the matrix"

outputs:
  gradle-wrapper-cache-hit:
    description: "A boolean value to indicate an exact match was found for Gradle wrapper cache"
    value: ${{steps.gradle-wrapper.outputs.cache-hit}}
  gradle-caches-cache-hit:
    description: "A boolean value to indicate an exact match was found for Gradle caches cache"
    value: ${{steps.gradle-caches.outputs.cache-hit}}

runs:
  using: composite
  steps:
  - name: Cache Gradle wrapper
    id: gradle-wrapper
    uses: actions/cache@v4
    with:
      lookup-only: '${{inputs.lookup-only}}'
      key: v${{inputs.cache-version}}-gradle-wrapper-${{hashFiles('**/gradle/wrapper/gradle-wrapper.properties', '**/gradle/gradle-daemon-jvm.properties')}}
      path: |
        ${{inputs.gradle-user-home}}/wrapper/dists
      enableCrossOsArchive: true
  - name: Cache Gradle caches
    id: gradle-caches
    uses: actions/cache@v4
    with:
      lookup-only: '${{inputs.lookup-only}}'
      key: v${{inputs.cache-version}}-gradle-caches-${{hashFiles('**/gradle/wrapper/gradle-wrapper.properties', '**/gradle/gradle-daemon-jvm.properties', '**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', '**/gradle.lockfile', '**/*-gradle.lockfile' , '**/gradle/*.versions.toml')}}
      path: |
        ${{inputs.gradle-user-home}}/caches
        ${{inputs.gradle-user-home}}/jdks
        ${{inputs.gradle-user-home}}/notifications
      enableCrossOsArchive: true
  - name: Cleanup Gradle wrapper cache
    if: ${{steps.gradle-wrapper.outputs.cache-hit != 'true' || steps.gradle-caches.outputs.cache-hit != 'true'}}
    uses: remal-github-actions/cache-gradle-cleanup-wrapper@v1

  - name: Setup Gradle Build Cache
    if: ${{inputs.build-cache-enabled == 'true' && (inputs.build-cache-for-branches-only == 'false' || github.ref_type == 'branch')}}
    shell: bash
    run: |
      mkdir -p ${{inputs.gradle-user-home}}
      echo "org.gradle.caching = true" >> ${{inputs.gradle-user-home}}/gradle.properties
      echo ::group::${{inputs.gradle-user-home}}/gradle.properties
      cat ${{inputs.gradle-user-home}}/gradle.properties
      echo "::endgroup::"

      mkdir -p ${{inputs.gradle-user-home}}/init.d
      cat <<EOF > ${{inputs.gradle-user-home}}/init.d/build-cache.gradle
      gradle.settingsEvaluated { settings ->
        settings.buildCache {
          local {
            directory = new File('${{inputs.gradle-user-home}}/.build-cache'.replaceFirst('^~/', System.getProperty('user.home') + '/'))
          }
        }
      }
      EOF
      echo ::group::${{inputs.gradle-user-home}}/init.d/build-cache.gradle
      cat ${{inputs.gradle-user-home}}/init.d/build-cache.gradle
      echo "::endgroup::"

  - name: Retrieve repository info
    if: ${{inputs.build-cache-enabled == 'true' && (inputs.build-cache-for-branches-only == 'false' || github.ref_type == 'branch')}}
    id: repository-info
    shell: bash
    run: |
      REPO_JSON=$(curl -s "${{github.api_url}}/repos/${{github.repository}}" -H "Authorization: token ${{github.token}}")
      DEFAULT_BRANCH=$(echo $REPO_JSON | jq -r '.default_branch')
      echo "default-branch=$DEFAULT_BRANCH" | tee -a $GITHUB_OUTPUT
  - name: Cache Gradle Build Cache for branch
    if: ${{inputs.build-cache-enabled == 'true' && (inputs.build-cache-for-branches-only == 'false' || github.ref_type == 'branch')}}
    uses: actions/cache@v4
    with:
      lookup-only: '${{inputs.lookup-only}}'
      key: v${{inputs.cache-version}}-gradle-build-cache-${{hashFiles('**/gradle/wrapper/gradle-wrapper.properties', '**/gradle/gradle-daemon-jvm.properties', '**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', '**/gradle.lockfile', '**/*-gradle.lockfile' , '**/gradle/*.versions.toml')}}-${{inputs.github-job}}-${{inputs.strategy-job-index||strategy.job-index||'0'}}/${{inputs.strategy-job-total||strategy.job-total||'0'}}-${{github.ref}}-${{github.sha}}-${{github.run_attempt}}
      restore-keys: |
        v${{inputs.cache-version}}-gradle-build-cache-${{hashFiles('**/gradle/wrapper/gradle-wrapper.properties', '**/gradle/gradle-daemon-jvm.properties', '**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', '**/gradle.lockfile', '**/*-gradle.lockfile' , '**/gradle/*.versions.toml')}}-${{inputs.github-job}}-${{inputs.strategy-job-index||strategy.job-index||'0'}}/${{inputs.strategy-job-total||strategy.job-total||'0'}}-${{github.ref}}-${{github.sha}}-
        v${{inputs.cache-version}}-gradle-build-cache-${{hashFiles('**/gradle/wrapper/gradle-wrapper.properties', '**/gradle/gradle-daemon-jvm.properties', '**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', '**/gradle.lockfile', '**/*-gradle.lockfile' , '**/gradle/*.versions.toml')}}-${{inputs.github-job}}-${{inputs.strategy-job-index||strategy.job-index||'0'}}/${{inputs.strategy-job-total||strategy.job-total||'0'}}-${{github.ref}}-
        v${{inputs.cache-version}}-gradle-build-cache-${{hashFiles('**/gradle/wrapper/gradle-wrapper.properties', '**/gradle/gradle-daemon-jvm.properties', '**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', '**/gradle.lockfile', '**/*-gradle.lockfile' , '**/gradle/*.versions.toml')}}-${{inputs.github-job}}-${{inputs.strategy-job-index||strategy.job-index||'0'}}/${{inputs.strategy-job-total||strategy.job-total||'0'}}-refs/heads/${{github.base_ref && github.base_ref || steps.repository-info.outputs.default-branch}}-
      path: |
        ${{inputs.gradle-user-home}}/.build-cache
      enableCrossOsArchive: true
